version: '3'
services:
  nginx:
    build: nginx
    links:
      - php
    ports:
      - "80:80"
  php:
    build: php
    links:
      - mysql
      - redis
      - mongo
    volumes:
      - ..:/app:rw
    ports:
      - "9000:9000"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"